version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  development-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: 'bash .circleci/development-deploy.sh'
  production-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: 'bash .circleci/production-deploy.sh'
workflows:
    build-and-test:
      jobs:
        - test
        - development-deploy:
            requires:
              - test
        - production-deploy:
          type: approval
            requires:
              - development-deploy
#        - development-deploy:
#            requires:
#              - build-and-test
