version: 2.1
orbs:
  azure-aks: circleci/azure-aks@0.2.1
  node: circleci/node@1.1.6
jobs:
  login-to-azure:
    executor: azure-aks/azure-docker
    steps:
      - checkout
      - run:
          command: az login -u andresram@unisabana.edu.co -p APFol9824XD
          name: Sign In to Azure CLI
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: cluster
          install-kubectl: true
          resource-group: Ubuntu
      - run:
          command: ls
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm build
            - run: kubectl get pods
workflows:
    build-and-test:
      jobs:
        - login-to-azure
        - test:
            filters:
              branches:
                only: master
