version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  development-deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:6e:15:88:0c:41:53:a2:b2:7e:24:59:25:ef:50:4f"
      - run:
          command: |
            ssh ubuntu@ec2-18-219-111-1.us-east-2.compute.amazonaws.com "bash deploy.sh"
  approval-job:

  production-deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:6e:15:88:0c:41:53:a2:b2:7e:24:59:25:ef:50:4f"
      - run:
          command: |
            ssh ubuntu@ec2-52-15-177-160.us-east-2.compute.amazonaws.com "bash deploy.sh"
workflows:
    build-and-test:
      jobs:
        - test
        - development-deploy:
            requires:
              - test
            filters:
              branches:
                only: master
        - approval-job:
            type: approval
            requires:
              - development-deploy
        - production-deploy:
            requires:
              - approval-job
            filters:
              branches:
                only: master
