version: 2.1
orbs:
  azure-aks: circleci/azure-aks@0.2.1
jobs:
  login-to-azure:
    executor: azure-aks/azure-docker
    steps:
      - checkout
      - run:
          command: az login -u andresram@unisabana.edu.co -p APFol9824XD
          name: Sign In to Azure CLI
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: cluster
          install-kubectl: true
          resource-group: Ubuntu
      - run:
          command: ls build
          name: Deleted last configmap
      - run:
          command: kubectl delete configmap web1-page --namespace ingress-basic
          name: Deleted last configmap
      - run:
          command: kubectl create configmap web1-page --from-file=web1/ --namespace ingress-basic
          name: Deleted last configmap
      - run:
          command: kubectl scale --replicas=0 deployment web1 --namespace ingress-basic
          name: Remove all the replicas
      - run:
          command: kubectl scale --replicas=1 deployment web1 --namespace ingress-basic
          name: Restart the replicas
workflows:
    build-and-test:
      jobs:
        - login-to-azure
