version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
      triggers: #use the triggers key to indicate a scheduled build
        - schedule:
            cron: "0 0 * * *" # use cron syntax to set the schedule
            filters:
              branches:
                only:
                  - master