version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  development-deploy:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          command: 'bash .circleci/development-deploy.sh'
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - development-deploy
#        - development-deploy:
#            requires:
#              - build-and-test
