version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  development-deploy:
    docker:
      - image: ubuntu:stable
    steps:
      - checkout
      - run:
          command: ssh -i ".circleci/instances.pem" root@ec2-18-219-111-1.us-east-2.compute.amazonaws.com
          command: ls
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - development-deploy
