version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  development-deploy:
    docker:
      - image: doomkin/ubuntu-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "81:6e:15:88:0c:41:53:a2:b2:7e:24:59:25:ef:50:4f"
      - run:
          command: 'bash .circleci/development-deploy.sh'
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - development-deploy
#        - development-deploy:
#            requires:
#              - build-and-test
